### ISSUE TITLE
포폴

### ISSUE THREAD

**Issue by Gongcu** [SunEom/SunEom#2]
@SunEom 

[추천]
1. 순서는 보통 최신순
- 일단 현재 오래된거~ 최근꺼 순으로 되어있긴한데 가능하면 최신순이 좋음. 
- 근데 만약, 최신 순에서 어필할게 너무 적다 싶으면 오래된 순으로 해도 괜찮은데 그정도가 아니라면 최신순 추천

2. 폰트
- 폰트는 Noto Sans나 나눔 고딕 추천 -> 웹에서 읽기 편한 폰트

3. 기술 추가
- 혹시 가능하다면 Unit Test를 프로젝트에 작성해보고 `기술` 탭에 unit test 추가 매우 추천
- 첫 페이지 Skills에도 unit test 추가하면 좋음
- 추가로 모집 공고를 자주 보다보면 `우대 사항`에 나오는 기술들을 가능한 많이 써보고 써놓으면 좋음
 - eg. `RxSwift`, `Alarmofie`, `Code Base Layout`, `Unit Test`
 - 이 때, 면접 질문 중 자주 나오고 면접관들이 보는게 '왜 썼냐?'임. 각 기술에 대해 장점과 단점을 말할 수 있어야 됨

4. 프로젝트에 대한 설명
- 줄글로 된 부분을 줄여도 좋을 것 같음
- 그리고 가능한 bullet list를 적극 활용 -> 가독성
- 그리고 만든 프로젝트가 어떤 앱인지에 대한 설명을 줄이고 이를 기능적인 설명으로 바꾸면 좋음. 면접관들은 어떤 기발한 아이디어의 프로젝트를 했는가는 아예 안보고 어떤 좋은 기술을 써서 기능을 구현했나만 봄

eg. Bad
```
- ~를 도울 수 있는 앱
- ~ 기능을 통해 ~ 도움 가능
```

```Good
- ~를 도울 수 있는 앱 // 프로젝트에 대한 설명은 1~2줄
- 소켓 통신을 통해 채팅 기능 구현
- HTTP Network는 RxAlamofire를 통해 비동기 처리
```

[NIT]
- 아이콘은 없어도 괜찮을지도?
![image](https://github.com/SunEom/SunEom/assets/30337408/d653a7b5-2b41-4695-9473-20372e228c0d)
  - 사실 읽는 사람 입장에서는 큰 의미를 둘 수 없어서 잠깐 시각적인 전환을 일으키는 것 같음
  - 만약 너무 비어서 아이콘을 추가한 느낌이라면 앱의 대표 기능에 대한 이미지를 한 개 정도 넣는것은 낫밷일듯.  (안 넣어도 괜찮음)
  - 혹은 아이콘을 프로젝트 제목 옆에 작게 추가하면 괜찮을듯
  
  
  
아마 대충 예시로 하나만 수정해보면
AS-IS
![image](https://github.com/SunEom/SunEom/assets/30337408/f8ea57e3-5362-481c-b981-c2dfe1573704)

TO-BE
- 프로젝트 요약
  - 영화 감상 리뷰 iOS 앱 입니다. // 조금 더 설명하긴 해야됨
  - RxSwift를 활용하여 Reactive Programming을 통해 프로젝트를 구현했습니다.
  - RxSwift와 Alamofire를 활용하여 네트워크 비동기 호출을 수행했습니다.
  - Code Base UI를 통해 기존 storyboard 방식에 비해 가독성 좋은 UI Code를 작성했습니다.

- 해결 경험, 느낀점? -> 제목은 잘 못짓겠ㅇ므.. ㅋㅋ
  - 기존에 특별한 Design 패턴 없이 아는 내에서 개발을 진행했습니다.
  - 그 과정에서 코드 구조가 점점 복잡해져 개발이 어려워졌습니다.
  - 그 과정에서 학부 수업 중 MVVM 디자인 패턴을 학습하게 되어 이를 프로젝트에 적용했습니다.
  - 그 이후 ~ 점이 개선되어 ~ 합니다.
  - RxSwift도 활용하여 Reactive Programming의 어떤 점이 굉장히 좋게 보였습니다. 허나 ~ 한 문제점이 있는 것 같습니다

**Comment by SunEom** [comment]
참고해서 수정해볼겡 🙃

**Comment by SunEom** [comment]
@Gongcu 

수정 한 번 했는데 봐주시면 감사합니다.

**Comment by Gongcu** [comment]
@SunEom 굿 좋은 것 같음 👍  
프로젝트 별로 사용한 기술이 좀 더 잘 보이면 좋을 것 같아서 순서가 조금 더 위쪽이면 괜찮을거 같기도 한데 이건 크게 중요하진 않을듯
